apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  destination:
    name: dev
    namespace: test
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: nginx-deployment
    repoURL: https://github.com/slodygin/argocd.git
  syncPolicy:
    automated: {}
